### ISSUE TITLE
SJSU-0002 Research on Monitors

### ISSUE THREAD

**Issue by itjinshan** [itjinshan/Smart-Mirror#2]
Research on suitable monitor based on following factors:

- Costs

- Size (W/H/L)

- Location and number of HDMI port

- Weight

**Comment by kev-96** [comment]
1) Sceptre E225W-19203R 22" Ultra Thin 75Hz 1080p LED Monitor 2x HDMI VGA Build-in Speakers, Metallic Black 2018

cost: $79.84

size: Without Stand (inch, W x H x D)- 19.56 x 11.49 x 1.22 Inch

location: amazon 2 HDMI Port

extra: built in speaker, also has audio output

link: https://www.amazon.com/Sceptre-E225W-19203R-Monitor-Speakers-Metallic/dp/B07774L6TT/ref=sr_1_7?keywords=monitor&qid=1561617987&s=gateway&sr=8-7



2) Sceptre 22 Inch LED 1080p Monitor E225W-1920 1920x1080 HDMI DVI VGA True Black, 2017

cost: $79.99

size: 20.04 x 7.17 x 14.69 in (with stand i think)

location: amazon, 1 HDMI Port

link: https://www.amazon.com/Sceptre-Monitor-Ports-Build-Speakers/dp/B00S8W8Z5E/ref=sr_1_27?keywords=monitor&qid=1561327712&refinements=p_n_condition-type%3A6461716011&rnid=6461714011&s=gateway&sr=8-27

**Comment by kev-96** [comment]
Sceptre 24-Inch LED HDTV E246BV-SR HDMI USB True Black

cost: $84.99

size: TV without Stand (Inch) 21.89” x 13.12” x 2.96”

location: amazon, 1 HDMI port, 1 USB port, VGA, audio in/out

link: https://www.amazon.com/Sceptre-inches-720p-LED-E246BV-SR/dp/B01N1GQC8P/ref=sr_1_1?keywords=tv&qid=1562018526&refinements=p_n_size_browse-bin%3A1232879011%2Cp_n_condition-type%3A2224371011&rnid=2224369011&s=electronics&sr=1-1

manual: https://www.sceptre.com/productSupports-406.html#support
