### ISSUE TITLE
SJSU-0003 Research On Raspberry Pi and Accessories

### ISSUE THREAD

**Issue by itjinshan** [itjinshan/Smart-Mirror#3]
Research on Raspberry Pi and necessary parts, such as camera, speaker, voice recorder and etc.

**Comment by HongbinZheng** [comment]
Microphone:
https://www.amazon.com/PoP-voice-Microphone-Omnidirectional-Smartphones/dp/B075VQ7VG7/ref=sr_1_244?keywords=usb+microphone&qid=1561652134&s=gateway&sr=8-244

Raspberry Pi would be 35 dollars
