### ISSUE TITLE
SJSU-0006 React Native Bluetooth Connection

### ISSUE THREAD

**Issue by itjinshan** [itjinshan/Smart-Mirror#7]
Research how to build Bluetooth connection in the app, and use Bluetooth to connect Raspberry Pi to wifi.

**Comment by kev-96** [comment]
react natvie bluetooth link: https://github.com/Polidea/react-native-ble-plx

**Comment by kev-96** [comment]
pi bluetooth: https://www.raspberrypi.org/forums/viewtopic.php?t=153685&p=1015370
